Design feedback pt3
input-output-hk/mantis-wallet pull request #65
Opened 2020-12-18 12:09 UTC by conqeror

2021-01-04 12:44 UTC, qwhex requested changes
Address book:
Copy button: please, set the proper cursor
The focus style is not really visible for the icons when navigating with the keyboard.

Tx history:
EditableAddress still has the old icons.
I'm not sure what's the plan with the sort-by dropdown (will you put it back with a different style?) - anyways, you forgot to remove the style override (.SortByDropdown).

2021-01-04 12:44 UTC, qwhex commented on src/address-book/AddressBook.tsx
> +                      className="clickable"
This has no effect.

2021-01-12 10:58 UTC, qwhex requested changes, later dismissed
> Address book copy button: please, set the proper cursor
> TxHistory: EditableAddress still has the old icons.

These are still not fixed.

2021-01-14 12:57 UTC, conqeror commented
@qwhex 
Made focused IconButtons stand out even more:
![image](https://user-images.githubusercontent.com/4038239/104593501-1430cb00-5670-11eb-91e7-ab0b2a5e8744.png)
& all the issues should be fixed by now (used IconButtons in tx list - not sure why I forgot about this :) and used proper cursor for all IconButtons).

Regarding dropdown, it's actually not present in designs at all. Discussed it with Russ and he asked me to just remove it. So I guess it's not worth to override the style for it when we actually don't use it :)

2021-01-15 12:29 UTC, qwhex approved these changes
:sunglasses:

2021-01-15 18:17 UTC, qwhex commented
I recommend setting up `data-testid`s to query the buttons.
Tip: by using `debug()` you can see the render output while fixing the tests locally, e.g.:
```ts
const {debug, getAllByTestId} = render(...)
debug()
```

2021-01-18 12:19 UTC, merged