[ETCM-513] Finish removing circular dependencies
input-output-hk/mantis-wallet pull request #76
Opened 2021-02-01 18:43 UTC by conqeror

# Description

I recommend going through changes commit by commit. Interesting changes include:

- using dynamic imports in the router with React.lazy + React.Suspense
- making types in history store more generic

2021-02-02 17:02 UTC, qwhex requested changes
The `main` build breaks with this PR :( 

I like the `React.lazy()` solution, but the loading spinner only shows up for approximately 50ms.
Wouldn't it be better to simply not show anything while the component loads?

Because it's not a webapp, every chunk should load pretty fast, except if you're using Mantis Wallet from a floppy disk. :smiley:

2021-02-02 17:02 UTC, qwhex commented on src/layout/Router.scss
> +@import '../themify', '../partial', '../vars';
There's a new file for non-rendering sass includes: `sass-includes.scss`
You can safely use it anywhere, because it doesn't change the style, those are just utilities.

2021-02-02 17:02 UTC, qwhex commented on src/routes-config.ts
> +      import('./address-book/AddressBook').then((module) => ({default: module.AddressBook})),
Note: I'd prefer starting to add `index.ts` files for component groups to simplify imports.
(not in this PR, but good to keep in mind)

2021-02-02 17:02 UTC, qwhex commented on package.json
> +    "eslint": "eslint src bin --ext .js,.ts,.tsx --max-warnings 0",
:sunglasses:

2021-02-02 17:02 UTC, qwhex commented on src/layout/Router.tsx
> +const LoadingScreen = (): JSX.Element => (
Can we merge this with `Loading.tsx` (or use that one?)
Also, please add a story for this if we keep this (see my main comment).

2021-02-02 17:02 UTC, qwhex commented on webpack.main.config.js
> +  output: {path: path.join(__dirname, 'build/main'), filename: '[name].bundle.js'},
This breaks the main build.
`yarn start-main` will use a previous build / or simply doesn't find the new one.

To reproduce:
- run `rm -rf build`
- run `yarn start-main`

I think we need this config change for the renderer (because of `React.lazy`) and not for the main build.

2021-02-03 08:47 UTC, conqeror commented on src/routes-config.ts
> +      import('./address-book/AddressBook').then((module) => ({default: module.AddressBook})),
Agreed :)

2021-02-03 09:17 UTC, conqeror commented on webpack.main.config.js
> +  output: {path: path.join(__dirname, 'build/main'), filename: '[name].bundle.js'},
Btw, webpack with this config still outputs just one file, so maybe we can just revert this change.

2021-02-03 17:13 UTC, qwhex approved these changes
LGTM!

2021-02-03 20:55 UTC, merged